version: '2'
services:
    bootstrap:
      networks:
        ethereum:
          aliases:
            - bootstrap
      image: fevenor/geth-with-intelligence
      container_name: bootstrap
      links:
        - statsmon
      entrypoint: /root/start.sh
      command: '--datadir=~/.ethereum/devchain --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --ipcapi="admin,db,eth,debug,miner,net,shh,txpool,personal,web3" --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=2333 --rpc --rpcaddr="0.0.0.0" init=/root/files/genesis.json'
      volumes:
        - ./files/genesis.json:/root/files/genesis.json:ro
        - ./files/keystore:/root/.ethereum/devchain/keystore:rw
        - /etc/localtime:/etc/localtime:ro
      ports:
        - "30303:30303"
        - "30303:30303/udp"
        - "8545:8545"

    eth:
      networks:
          ethereum:
      image: fevenor/geth-with-intelligence
      links: 
        - statsmon
        - bootstrap
      entrypoint: /root/start.sh
      command: --datadir=~/.ethereum/devchain --rpccorsdomain='*' --networkid=2333 --rpc init=/root/files/genesis.json --bootnodes='enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@bootstrap:30303'
      volumes:
        - ./files/genesis.json:/root/files/genesis.json:ro
        - ./files/keystore:/root/.ethereum/devchain/keystore:rw
        - /etc/localtime:/etc/localtime:ro
  
    miner:
      networks:
          ethereum:
      image: fevenor/geth-with-intelligence
      links: 
        - statsmon
        - bootstrap
      entrypoint: /root/start.sh
      command: --datadir=~/.ethereum/devchain --rpccorsdomain='*' --networkid=2333 --rpc init=/root/files/genesis.json --bootnodes='enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@bootstrap:30303 --mine --minerthreads=1'
      volumes:
        - ./files/genesis.json:/root/files/genesis.json:ro
        - ./files/keystore:/root/.ethereum/devchain/keystore:rw
        - /etc/localtime:/etc/localtime:ro
  
    statsmon:
      networks:
        ethereum:
          aliases:
            - statsmon
      image: fevenor/eth-netstats
      container_name: statsmon
      environment:
        - WS_SECRET=eth-net-stats-secret
      ports:
        - "3000:3000"

networks:
  ethereum:
    driver: overlay

